In [2]:
import numpy as np

In [3]:
arr=np.array(11)
#array function with value 11. It is known as scalar/number or 0-D array
print("The array is:", arr )
#This type of array having a single number only is called 0-D array

The array is: 11


In [4]:
# type(): type() is a built-in python function that determines the type of array
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
# We may use extended syntax with various parameters:-
# numpy.array(object, dtype, copy=True, order=None, subclass=False,ndim)
# Details of paramteres are as follows:
# 1. object: It represents python collections object like list, tuple, dictionary.
# 2. dtype: It is possible to assign a data type to the array elements.
# 3. copy: This parameter that suggests if the object is copied or not.
# 4. order: 2 possible value available-1.

In [5]:
# Example to create an 1-D array using the list object
arr=np.array([10,11,12,13,14,15])
print(arr)     #Array syntax has list brackets but no commas

[10 11 12 13 14 15]


In [6]:
print(arr[0], arr[1], arr[5]) 

10 11 15


In [9]:
arr=np.array({'h','e','l','l','o'})
print(arr)

{'h', 'o', 'e', 'l'}


In [11]:
# Example to create a (multi-dimensional) 2-D array object. 
# An array that has 1-D arrays as its elements is called a 2-D array
# These are often used to represt matrix or 2nd order tensors
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print("The size of array: ", arr1.size)  #size property gives
print(type(arr1))
print("arr1[0,0]: ", arr1[0,0]) #arr1[row number, col number]
print("arr1[2][1]: ", arr1[2][1])  #arr1[row number][col number]
print(type(arr1[0,0]))  #arr1[0][0]=10
print(type(arr1[1,1]))   #arr1[1][1]=50

# To check the data type of each array item, the dtype function is used.
print('The datatype of each element of arr1: ', arr1.dtype)

arr2=np.array(['a','b','c','d','e'])
print(arr2)
print(arr2.size)
print(type(arr2))
print(type(arr2[0]))
print(arr2.dtype)  #U1 means unicode string

[[10 20 30]
 [40 50 60]
 [70 80 90]]
The size of array:  9
<class 'numpy.ndarray'>
arr1[0,0]:  10
arr1[2][1]:  80
<class 'numpy.int32'>
<class 'numpy.int32'>
The datatype of each element of arr1:  int32
['a' 'b' 'c' 'd' 'e']
5
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<U1


In [14]:
# We can reshape the array by changing the number of rows and columns of the N-D array
# reshape() function is used to reshape the array
# It takes two parameters- row and columns defining the new shape of the array.
# Rules of reshape: The reshaped array must maintain size compatibility
arr=np.array([[1,2],[3,4],[5,6]])  #3 rows and 2 columns -> 3*2=6
print("printing original array 1")
print(arr)
arr=arr.reshape(2,3)
print("printing the reshaped array 2")
print(arr)
arr=arr.reshape(1,6)
print("printing the reshaped array 3")
print(arr)
arr=arr.reshape(3,2)
print("printing the reshaped array 4")
print(arr)
arr=arr.reshape(6,1)
print("printing the reshaped array 5")
print(arr)

# arr=arr.reshape(2,2) : it gives error because we are trying to reshape with incompatible row and column number : 2*2=4

printing original array 1
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array 2
[[1 2 3]
 [4 5 6]]
printing the reshaped array 3
[[1 2 3 4 5 6]]
printing the reshaped array 4
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array 5
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
# Demo of 3-D arrays
# An array having 2-D arrays as its element is called 3-D array and represents a 3D array
arr2=np.array([[[5,6,7],[8,9,10]],[[11,12,13],[14,15,16]]])
arr3=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[44,55,66],[77,88,99]]])
print(arr2)
print(arr2.shape)   #gives output as: (no. of 2D array/ small components, no. of row, no. of columns)
print(arr3)
print(arr3.shape)

[[[ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]]]
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[44 55 66]
  [77 88 99]]]
(3, 2, 3)


In [9]:
# To convert datatype
arr1=np.array([(10,1),(20,2),(30,3),(40,5)], complex)
print(arr1)
print(arr1.shape)

[[10.+0.j  1.+0.j]
 [20.+0.j  2.+0.j]
 [30.+0.j  3.+0.j]
 [40.+0.j  5.+0.j]]
(4, 2)


In [31]:
# The ndim property can be used to find the dimensions of the array (just see the no. of brackets at the end of array, irrespective of no. of elements present in the array)
arr2=np.array(10)
print(arr2.ndim)
arr3=np.array([1,2,3,4,5,6,7,8])
print(arr3.ndim)
arr4=np.array([[10,20,30],[100,200,300]])
print(arr4.ndim)

0
1
2


In [38]:
# We can assign any number of dimensions to an array
# We can define the number of dimensions by using the ndim argument while defining and array
# Array defined with 4 dimensions as 4-D array
arr3=np.array([1,2,3,4,5,6], ndmin=4, dtype=float)
print(arr3)
print(arr3.ndim)

[[[[1. 2. 3. 4. 5. 6.]]]]
4


In [40]:
arr2=np.array([[[5,6,7],[8,9,10]],[[11,12,13],[14,15,16]]])
print(arr2)
# syntax of accessing 3-D array element = array_name[no. of 2-D array, row_number,col_number]
print(arr2[0,0,2])
print(arr2[0,1,2])
print(arr2[1,0,2])
print(arr2[1,0,2])
print(arr2[1,1,2])

[[[ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]]]
7
10
13
13
16


In [41]:
# Demo of negative indexing i.e. starting from the right end and moving to left
# Accessing last element in 1-D
arr4=np.array([1,2,3,4,5])
print("The last element in 1-D array; ", arr4[-1])

arr5=np.array([[1,2,3],[4,5,6]])
print("the last element in 2-D array 0th row: ", arr5[0][-1])
print("the last element in 2-D array 1th row: ", arr5[1][-1])
print("element 5 in 2-D array 1st row: ", arr5[-1][-2])

The last element in 1-D array;  5
the last element in 2-D array 0th row:  3
the last element in 2-D array 1th row:  6
element 5 in 2-D array 1st row:  5


In [42]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])
print(arr[::-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [44]:
# numpy.arange(): creates an array by using the evenly spaces values over the given...
# syntax: numpy.arange(start_index, stop_index, step, dtype)
arr1=np.arange(1,50,2,float)
print(arr1)
arr2=np.arange(10,100.5, 3.3, float)
print(arr2)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49.]
[10.  13.3 16.6 19.9 23.2 26.5 29.8 33.1 36.4 39.7 43.  46.3 49.6 52.9
 56.2 59.5 62.8 66.1 69.4 72.7 76.  79.3 82.6 85.9 89.2 92.5 95.8 99.1]


In [11]:
# linspace(): functions returns the evenly spaces values over the given interval
# prints 10 values which are evemly spaces over the given interval 1-20
arr=np.linspace(1,20,10)
print(arr)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [47]:
# N-D array can be represented using axis such that axis=0 defined columns and axis=1 define....
# use axis to implement row-level and column-level calculations.
# Demo to find maximum element, minimum element, and the addition of all the row/column...
arr=np.array([[1,2,3],[10,1,6]])
print(arr)
print("the maximum element in each columns are:", arr.max(axis=0))
print("the maximum element in each rows are:", arr.max(axis=1))
print("the minimum element in each columns are:", arr.min(axis=0))
print("the minimum element in each columns are:", arr.min(axis=1))
print("the sum of all elements column-wise: ", arr.sum(axis=0))
print("the sum of all elements row-wise: ", arr.sum(axis=1))

[[ 1  2  3]
 [10  1  6]]
the maximum element in each columns are: [10  2  6]
the maximum element in each rows are: [ 3 10]
the minimum element in each columns are: [1 1 3]
the minimum element in each columns are: [1 1]
the sum of all elements column-wise:  [11  3  9]
the sum of all elements row-wise:  [ 6 17]


In [49]:
# for finding square root and standard deviation ot the array elements we can use sqrt()....
arr1=np.array([[9,5,1],[16,20,30]])
print(np.sqrt(arr1))
print(np.std(arr1))
arr2=np.array([20,2,7,1,34])
print(np.mean(arr2))
arr3=np.array([[[5,6,7],[8,9,10]],[[11,12,13],[14,15,16]]])
print(np.mean(arr3))
print("the mean value column-wise:", np.mean(arr3,axis=0))
print("the mean value row-wise:", np.mean(arr3,axis=1))

[[3.         2.23606798 1.        ]
 [4.         4.47213595 5.47722558]]
9.742518497116988
12.8
10.5
the mean value column-wise: [[ 8.  9. 10.]
 [11. 12. 13.]]
the mean value row-wise: [[ 6.5  7.5  8.5]
 [12.5 13.5 14.5]]


In [53]:
# Arithmetic operations are performed on arrays
arr1=np.array([[1,4,6],[5,10,20]])
arr2=np.array([[1,2,3],[110,50,80]])
print("First array: \n",arr1)
print("Second array: \n",arr2)
print("Addition: \n",arr1+arr2)
print("Subtraction: \n",arr1-arr2)
print("Multiplication: \n",arr1*arr2)
print("Division: \n",arr1/arr2)

First array: 
 [[ 1  4  6]
 [ 5 10 20]]
Second array: 
 [[  1   2   3]
 [110  50  80]]
Addition: 
 [[  2   6   9]
 [115  60 100]]
Subtraction: 
 [[   0    2    3]
 [-105  -40  -60]]
Multiplication: 
 [[   1    8   18]
 [ 550  500 1600]]
Division: 
 [[1.         2.         2.        ]
 [0.04545455 0.2        0.25      ]]


In [61]:
# numpy.empty
arr1=np.empty((3,3),dtype=int, order='F')
print(arr1)
arr1=np.empty((3,3),dtype=int, order='C')
print(arr1)

# numpy.zeroes
arr2=np.zeros((3,4),dtype=int, order='C')
print(arr2)

# numpy.ones
arr3=np.ones((3,4),dtype=int)
print(arr3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [65]:
# iteration in 1-D array
arr1=np.array([1,2,3,4,5,5,6,7,8,9,10])
for i in arr1:
    print(i)

1
2
3
4
5
5
6
7
8
9
10


In [66]:
# Iteration of each row in 2-d array
arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])
# for loop to print each row of 2-d array
count:int=0   #declaring a variable as integer type in advance and giving default value=0
for row in arr2:
    count = count +1
    print("row",count,":", row)

# for loop to print each scalar or individual elements
print("All elements of array are:")
for row in arr2:
    for i in row:
        print(i)

row 1 : [1 2 3]
row 2 : [4 5 6]
row 3 : [7 8 9]
All elements of array are:
1
2
3
4
5
6
7
8
9


In [5]:
# iteration in 3-D array
arr1=np.array([[[1,2,3],[4,5,6]]])
for twodarray in arr1:
    for row in twodarray:
        for i in row:
            print(i)

1
2
3
4
5
6


In [14]:
# NumPy contains a matrix Library called numpy.matlib which is used to configure
# 1. numpy.matlib.empty() function: It is used to return a matrix
#Syntax: numpy.matlib.empty (shape, dtype, order) 
# 1 shape: Shape of the matrix.
# 2 type: Data type of the matrix.
# 3 order: Insertion order of the matrix, i.e. C or F.
import numpy
import numpy.matlib
print (numpy.matlib.empty ((3,4)))

[[1.54779732e-307 7.32949229e-308 5.74877383e-306 0.00000000e+000]
 [2.26553299e-081 5.26488672e+170 4.53234115e+257 9.06968600e+276]
 [1.65368296e-080 5.73348318e+169 3.57718699e-062 5.40375527e-310]]


In [12]:
# 2. numpy.matlib.zeros) : Creates a matrix where the entries are initialized with zero
print (numpy.matlib.zeros ((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# 3. numpy.matlib.ones() : Creates a martix with all elements initialized with one
print(numpy.matlib.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# numpy.matlib.eye() : diagonal elements initialized with one and all other elements zero
print(numpy.matlib.eye(3,3))
print(numpy.matlib.eye(3,2))
print(numpy.matlib.eye(4,4))
print(numpy.matlib.eye(4,5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [18]:
# numpy.matlib.identity(): creates an identity matrix of the given size.
# similiar to matlib.eye()
print(numpy.matlib.identity(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [19]:
# numpy.matlib.rand
print(numpy.matlib.rand(5,4))

[[0.15200575 0.61836441 0.60199509 0.59421364]
 [0.52240717 0.45665696 0.75864928 0.25278021]
 [0.32296427 0.70165732 0.50491907 0.9357274 ]
 [0.3901913  0.57310861 0.05797156 0.8008912 ]
 [0.72675396 0.35639983 0.7294212  0.82438783]]


In [20]:
# PANDAS

In [21]:
import pandas as pd
import numpy as np

In [22]:
print(pd.__version__)
print(np.__version__)

1.5.3
1.26.1


In [23]:
# Creating an empty series
series1=pd.Series()
print(series1)

<ipython-input-23-519664585662>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  series1=pd.Series()


Series([], dtype: float64)


In [24]:
# Creating a series from array/list
arr1=np.array(['h','e','l','l','o'])
series2=pd.Series(arr1)
print(series2)

0    h
1    e
2    l
3    l
4    o
dtype: object


In [25]:
# Creating an empty dataframe
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [26]:
# DataFrame can be created using a single list or a list of lists

# list of strings
list1=['hello','all','users']
df1=pd.DataFrame(list1)
print(df1)

       0
0  hello
1    all
2  users


In [27]:
list1=[('hello','all','users'),[1,2,3,4,5],['a','b','c','d']]
df1=pd.DataFrame(list1)
print(df1)

       0    1      2     3    4
0  hello  all  users  None  NaN
1      1    2      3     4  5.0
2      a    b      c     d  NaN
