In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
arr1=np.array([11,22,33,44,55])
print("The array is: ",arr1)

The array is:  [11 22 33 44 55]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2=np.array((77,88,99,100))
print("The array is: ", arr2)
print(type(arr2))

The array is:  [ 77  88  99 100]
<class 'numpy.ndarray'>


In [6]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print("The number of dimensions: ", arr3.ndim)
print("The shape of array: ", arr3.shape)

[[1 2 3]
 [4 5 6]]
The number of dimensions:  2
The shape of array:  (2, 3)


In [8]:
arr4=np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]], [[111,222,333],[444,555,666]]])
print(arr4)
print("The number of dimensions: ", arr4.ndim)
print("The shape of array: ", arr4.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[ 11  22  33]
  [ 44  55  66]]

 [[111 222 333]
  [444 555 666]]]
The number of dimensions:  3
The shape of array:  (3, 2, 3)
